sudo: required

language: clojure

addons:
  debug: true
  artifacts: true
  s3_region: "eu-west-1"
  paths:
    - db-docs/schemadocs
#   - $(git ls-files -o | tr "\n" ":")
#   - $(ls /var/log/*.log | tr "\n" ":")
#   - $HOME/some/other/thing.log

deploy:
  provider: s3
  skip_cleanup: true
  local_dir: db-docs/schemadocs

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - cd ttk-db
  
before_script:
  - psql --file=../env/db/dev.sql

script:
  - lein run 'postgresql://ttk_adm:ttk-adm@127.0.0.1:5432/ttk' -u ttk_user --aituhaku-username aituhaku_user --clear -t
  - cd ../db-docs
  - generate-schemadocs.sh

after_script:
  - ls -latr schemadocs