sudo: required
language: clojure
addons:
  postgresql: '9.3'

deploy:
  provider: s3
  access_key_id: "$ARTIFACTS_KEY"  
  secret_access_key:
    secure: YIiyrktBhpfg1AS5eQVOJeUzVuLxP2AsQgdQI2CksD06oigyOqOLopkDOXAa5rNzNv6IIU63Sk/SNGtDpGx2Vd6ynDA28RL5/PWS1Gx9vTrsZeyEL2TU9gjA9PsgjMoBTtRR7V3GJIH3jyWlllat5CP62VhV60Ge9Ai5wElpUwojoIsRGJxyE1Q/xfv37X2u1wYCK376RXlxotME6G4Ugls9zqMVgAeypqIqaWeVFJ9bovHQvQpj7iqVymmNY7dCCIm4TDPcUezoKsDHWlUe98w4cvvyOGO8HJVTMOvnLzNPRvN4snvulnJEDTxPwq5m5jpD99wxZpJdi8IvzH0jbitGXWzg7MUMfI+0xAWrH+cWENebPoCXZjj986q34Qm1m7XiJP1t7ZgtFmTO7kAyMaflilwFLc1Pr4icsuMTh7/Z//HdKlfunrJOUedk2mdlZdf4SLbZUxSJMgGyP53pQRcsbalzjaY6g2/pRK4dNWLhRknAZGTYpMXN3kTW9KYAozZMXaE2l9lnx3IyWR2PGX3czp7Z84PBxWsMwXHJLc+YWMu9uzZs5llMqMSD3nWe8gwWIAVLLxCRBclhc5G1fQGV3nP7WBeLCkRz67aZSFRUqJGx2CkXcbBGD33G8DP4PKv0eDxK/A89mnIPyNDceUYs+36DS/JzJgQRsUkzg38=
  bucket: opetushallitus-docs
  local-dir: schemadocs
  acl: public_read
  skip_cleanup: true
  on:
    repo: lokori/aitu

services:
- postgresql

before_install:
- cd ttk-db

before_script:
- psql --file=../env/db/dev.sql

script:
- lein run 'postgresql://ttk_adm:ttk-adm@127.0.0.1:5432/ttk' -u ttk_user --aituhaku-username
  aituhaku_user --clear -t
- cd ../db-docs
- generate-schemadocs.sh

after_script:
- ls -latr schemadocs
